// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPmDCkgbAUBJ-8_4w21gIALYstYdGK6PY',
    appId: '1:852045336775:web:afd29ba86c49e4e2ceeee2',
    messagingSenderId: '852045336775',
    projectId: 'budapp-6e0a7',
    authDomain: 'budapp-6e0a7.firebaseapp.com',
    storageBucket: 'budapp-6e0a7.firebasestorage.app',
    measurementId: 'G-8QQE1QS1Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-AgKSB9Wm_yeQaA35Y3yz-C0Ax5iCSI0',
    appId: '1:852045336775:android:e4f78417c254c7f6ceeee2',
    messagingSenderId: '852045336775',
    projectId: 'budapp-6e0a7',
    storageBucket: 'budapp-6e0a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRUJbWYksJSIyF3Gg6XFFueeQZ_jbNvw',
    appId: '1:852045336775:ios:50755777082aad0aceeee2',
    messagingSenderId: '852045336775',
    projectId: 'budapp-6e0a7',
    storageBucket: 'budapp-6e0a7.firebasestorage.app',
    iosBundleId: 'com.example.budapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRUJbWYksJSIyF3Gg6XFFueeQZ_jbNvw',
    appId: '1:852045336775:ios:50755777082aad0aceeee2',
    messagingSenderId: '852045336775',
    projectId: 'budapp-6e0a7',
    storageBucket: 'budapp-6e0a7.firebasestorage.app',
    iosBundleId: 'com.example.budapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPmDCkgbAUBJ-8_4w21gIALYstYdGK6PY',
    appId: '1:852045336775:web:043788436c9c3a20ceeee2',
    messagingSenderId: '852045336775',
    projectId: 'budapp-6e0a7',
    authDomain: 'budapp-6e0a7.firebaseapp.com',
    storageBucket: 'budapp-6e0a7.firebasestorage.app',
    measurementId: 'G-JTKJQ5JMW6',
  );

}
